version: '3'
services:
#  runner:
#   image: api_runner
#   links:
#    - server:oasis_api_server
  server:
   image: oasis_api_server:mysql
   build:
     context: .
     dockerfile: Dockerfile.oasis_api_server.mysql
   ports:
     - 8000:8000
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     - OASIS_API_DEBUG=1
     - OASIS_API_RABBIT_HOST=rabbit
     - OASIS_API_RABBIT_PORT=5672
     - OASIS_API_RABBIT_USER=rabbit
     - OASIS_API_RABBIT_PASS=rabbit
     - OASIS_API_SERVER_DB_HOST=server-db
     - OASIS_API_SERVER_DB_PASS=oasis
     - OASIS_API_SERVER_DB_USER=oasis
     - OASIS_API_SERVER_DB_NAME=oasis
     - OASIS_API_SERVER_DB_PORT=3306
     - OASIS_API_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_API_CELERY_DB_HOST=celery-db
     - OASIS_API_CELERY_DB_PASS=password
     - OASIS_API_CELERY_DB_USER=celery
     - OASIS_API_CELERY_DB_NAME=celery
     - OASIS_API_CELERY_DB_PORT=3306
   volumes:
#     - ./log:/var/log/oasis:rw
     - ${OASIS_API_MEDIA_ROOT:-./docker-shared-fs}:/shared-fs
  worker:
    image: model_execution_worker
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - MODEL_SUPPLIER_ID=OasisIM
     - MODEL_ID=PiWind
     - MODEL_VERSION_ID=1
     - OASIS_API_RABBIT_HOST=rabbit
     - OASIS_API_RABBIT_PORT=5672
     - OASIS_API_RABBIT_USER=rabbit
     - OASIS_API_RABBIT_PASS=rabbit
     - OASIS_API_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_API_CELERY_DB_HOST=celery-db
     - OASIS_API_CELERY_DB_PASS=password
     - OASIS_API_CELERY_DB_USER=celery
     - OASIS_API_CELERY_DB_NAME=celery
     - OASIS_API_CELERY_DB_PORT=3306
    volumes:
#     - ./log:/var/log/oasis:rw
     - ./upload:/var/oasis/upload:rw
     - ./download:/var/oasis/download:rw
     - ./data/static:/var/oasis/model_data/OasisIM/1:rw
     - ${OASIS_API_MEDIA_ROOT:-./docker-shared-fs}:/shared-fs
  server-db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=oasis
      - MYSQL_PASSWORD=oasis
      - MYSQL_DATABASE=oasis
  celery-db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery 
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "15672:15672"
  flower:
    image: iserko/docker-celery-flower 
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:rabbit@rabbit:5672
    entrypoint:
      - flower 
      - --port=5555 
      - --broker_api=http://rabbit:rabbit@rabbit:5672/api/"
    links:
     - celery-db
     - rabbit
